# Generated by Django 4.1.5 on 2023-01-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vueBackend', '0002_alter_todotask_taskid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='label',
            field=models.TimeField(max_length=100),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='taskId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
