# Generated by Django 4.1.5 on 2023-01-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vueBackend', '0003_alter_todotask_label_alter_todotask_taskid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='label',
            field=models.CharField(max_length=100),
        ),
    ]
